{% extends "report/base.html.tpl" %}
{% block title %}Inventory Report{% endblock %}
{% block report_status %}
    <div class="report-status report-status-inventory">Inventory</div>
{% endblock %}
{% block report_header %}
    <h1 class="report-subject">Inventory Report</h1>
{% endblock %}
{% block report_timestamp %}
    <div class="report-timestamp">{{ generated_at }}</div>
{% endblock %}
{% block report_meta_title %}Summary{% endblock %}
{% block report_meta %}
    <dt class="report-dt">Generated At</dt>
    <dd class="report-dd report-dd-mono">{{ generated_at }}</dd>
    <dt class="report-dt">Orders Included</dt>
    <dd class="report-dd">{{ orders_count }}</dd>
    <dt class="report-dt">Order References</dt>
    <dd class="report-dd report-dd-mono">
        {% for entry in order_references %}<a href="{{ url_for('order_api.report', id = entry.id) }}" target="_blank">{{ entry.reference }}</a>{% if not loop.last %}, {% endif %}{% else %}-{% endfor %}
    </dd>
    <dt class="report-dt">Total Units</dt>
    <dd class="report-dd">{{ total_units }} x</dd>
    <dt class="report-dt">Generated By</dt>
    <dd class="report-dd">{{ generated_by|default("-", True) }}</dd>
{% endblock %}
{% block report_body %}
    <section class="report-section">
        <h2 class="report-section-title">Line Items</h2>
        <table class="report-table">
            <thead>
                <tr>
                    <th class="report-table-check"><span class="report-check"></span></th>
                    {% if thumbnail %}<th class="report-table-thumbnail"></th>{% endif %}
                    {% if report_type == "product" %}
                        <th>Product Reference</th>
                        <th>Order Reference</th>
                    {% else %}
                        <th>Order Reference</th>
                        <th>Product Reference</th>
                    {% endif %}
                    <th>Short Description</th>
                    <th>Gender</th>
                    <th>Size</th>
                    <th class="report-table-quantity">Quantity</th>
                </tr>
            </thead>
            <tbody>
                {% for row in rows %}
                    <tr{% if not loop.first and ((report_type == "product" and not loop.previtem.product_reference == row.product_reference) or (report_type == "order" and not loop.previtem.order_id == row.order_id)) %} class="report-table-order-first"{% endif %}>
                        <td class="report-table-check"><span class="report-check"></span></td>
                        {% if thumbnail %}
                            <td class="report-table-thumbnail">
                                {% if row.thumbnail_url %}
                                    <img class="report-thumbnail" src="{{ row.thumbnail_url }}" alt="{{ row.product_reference }}" />
                                {% endif %}
                            </td>
                        {% endif %}
                        {% if report_type == "product" %}
                            <td class="report-table-mono">{{ row.product_reference }}</td>
                            <td class="report-table-mono"><a href="{{ url_for('order_api.report', id = row.order_id) }}" target="_blank">{{ row.order_reference }}</a></td>
                        {% else %}
                            <td class="report-table-mono"><a href="{{ url_for('order_api.report', id = row.order_id) }}" target="_blank">{{ row.order_reference }}</a></td>
                            <td class="report-table-mono">{{ row.product_reference }}</td>
                        {% endif %}
                        <td>{{ row.short_description }}</td>
                        <td>{{ row.gender|default("-", True) }}</td>
                        <td class="report-table-mono">{{ row.size|default("-", True) }}</td>
                        <td class="report-table-quantity">{{ row.quantity }} x</td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td class="report-table-check"></td>
                    {% if thumbnail %}<td class="report-table-thumbnail"></td>{% endif %}
                    <td colspan="5">Total</td>
                    <td class="report-table-quantity">{{ total_units }} x</td>
                </tr>
            </tfoot>
        </table>
    </section>
{% endblock %}
{% block report_footer %}
    Budy Inventory Report
{% endblock %}
