{% extends "report/base.html.tpl" %}
{% block title %}Inventory Report{% endblock %}
{% block report_status %}
    <div class="report-status report-status-inventory">Inventory</div>
{% endblock %}
{% block report_header %}
    <h1 class="report-subject">Inventory Report</h1>
{% endblock %}
{% block report_timestamp %}
    <div class="report-timestamp">{{ generated_at }}</div>
{% endblock %}
{% block report_meta_title %}Summary{% endblock %}
{% block report_meta %}
    <dt class="report-dt">Generated At</dt>
    <dd class="report-dd report-dd-mono">{{ generated_at }}</dd>
    <dt class="report-dt">Orders Included</dt>
    <dd class="report-dd">{{ orders_count }}</dd>
    <dt class="report-dt">Order References</dt>
    <dd class="report-dd report-dd-mono">{{ order_references|join(", ") or "-" }}</dd>
    <dt class="report-dt">Total Units</dt>
    <dd class="report-dd">{{ total_units }}</dd>
    <dt class="report-dt">Generated By</dt>
    <dd class="report-dd">{{ generated_by or "-" }}</dd>
{% endblock %}
{% block report_body %}
    <section class="report-section">
        <h2 class="report-section-title">Line Items</h2>
        <table class="report-table">
            <thead>
                <tr>
                    <th class="report-table-check"><span class="report-check"></span></th>
                    <th>Order Reference</th>
                    <th>Product Reference</th>
                    <th>Short Description</th>
                    <th>Gender</th>
                    <th>Size</th>
                    <th class="report-table-quantity">Quantity</th>
                </tr>
            </thead>
            <tbody>
                {% for row in rows %}
                    <tr>
                        <td class="report-table-check"><span class="report-check"></span></td>
                        <td class="report-table-mono">{{ row.order_reference }}</td>
                        <td class="report-table-mono">{{ row.product_reference }}</td>
                        <td>{{ row.short_description }}</td>
                        <td>{{ row.gender }}</td>
                        <td class="report-table-mono">{{ row.size }}</td>
                        <td class="report-table-quantity">{{ row.quantity }}</td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td class="report-table-check"></td>
                    <td colspan="5">Total</td>
                    <td class="report-table-quantity">{{ total_units }}</td>
                </tr>
            </tfoot>
        </table>
    </section>
{% endblock %}
{% block report_footer %}
    Budy Inventory Report
{% endblock %}
