{% extends "report/base.html.tpl" %}
{% block title %}Order {{ order.reference }}{% endblock %}
{% block report_status %}
    <div class="report-status report-status-{{ order.status }}">{{ order.status }}</div>
{% endblock %}
{% block report_header %}
    <h1 class="report-subject">Order {{ order.reference }}</h1>
{% endblock %}
{% block report_timestamp %}
    <div class="report-timestamp">{{ generated_at }}</div>
{% endblock %}
{% block report_meta_title %}Summary{% endblock %}
{% block report_meta %}
    <dt class="report-dt">Reference</dt>
    <dd class="report-dd report-dd-mono">{{ order.reference }}</dd>
    <dt class="report-dt">Status</dt>
    <dd class="report-dd">{{ order.status }}</dd>
    <dt class="report-dt">Created</dt>
    <dd class="report-dd report-dd-mono">{{ order.created_d.strftime("%d/%m/%Y %H:%M:%S") }}</dd>
    <dt class="report-dt">Paid</dt>
    <dd class="report-dd">{{ "Yes" if order.paid else "No" }}</dd>
    <dt class="report-dt">Currency</dt>
    <dd class="report-dd report-dd-mono">{{ order.currency or "-" }}</dd>
    <dt class="report-dt">Generated At</dt>
    <dd class="report-dd report-dd-mono">{{ generated_at }}</dd>
    <dt class="report-dt">Generated By</dt>
    <dd class="report-dd">{{ generated_by or "-" }}</dd>
{% endblock %}
{% block report_body %}
    {% if order.email or order.account %}
        <section class="report-section report-section-card">
            <h2 class="report-section-title">Customer</h2>
            <dl class="report-dl">
                {% if order.email %}
                    <dt class="report-dt">Email</dt>
                    <dd class="report-dd report-dd-mono">{{ order.email }}</dd>
                {% endif %}
                {% if order.account %}
                    <dt class="report-dt">Account</dt>
                    <dd class="report-dd report-dd-mono">{{ order.account.username }}</dd>
                {% endif %}
            </dl>
        </section>
    {% endif %}
    {% if order.shipping_address or order.billing_address %}
        <section class="report-section">
            <div class="report-dl-pair">
                {% if order.shipping_address %}
                    <div>
                        <h2 class="report-section-title">Shipping Address</h2>
                        <dl class="report-dl">
                            <dt class="report-dt">Name</dt>
                            <dd class="report-dd">{{ order.shipping_address.full_name }}</dd>
                            <dt class="report-dt">Address</dt>
                            <dd class="report-dd">{{ order.shipping_address.address }}</dd>
                            {% if order.shipping_address.address_extra %}
                                <dt class="report-dt">Address Extra</dt>
                                <dd class="report-dd">{{ order.shipping_address.address_extra }}</dd>
                            {% endif %}
                            <dt class="report-dt">City</dt>
                            <dd class="report-dd">{{ order.shipping_address.city }}</dd>
                            <dt class="report-dt">Postal Code</dt>
                            <dd class="report-dd report-dd-mono">{{ order.shipping_address.postal_code or "-" }}</dd>
                            {% if order.shipping_address.state %}
                                <dt class="report-dt">State</dt>
                                <dd class="report-dd">{{ order.shipping_address.state }}</dd>
                            {% endif %}
                            <dt class="report-dt">Country</dt>
                            <dd class="report-dd report-dd-mono">{{ order.shipping_address.country or "-" }}</dd>
                            {% if order.shipping_address.phone_number %}
                                <dt class="report-dt">Phone</dt>
                                <dd class="report-dd report-dd-mono">{{ order.shipping_address.phone_number }}</dd>
                            {% endif %}
                        </dl>
                    </div>
                {% endif %}
                {% if order.billing_address %}
                    <div>
                        <h2 class="report-section-title">Billing Address</h2>
                        <dl class="report-dl">
                            <dt class="report-dt">Name</dt>
                            <dd class="report-dd">{{ order.billing_address.full_name }}</dd>
                            <dt class="report-dt">Address</dt>
                            <dd class="report-dd">{{ order.billing_address.address }}</dd>
                            {% if order.billing_address.address_extra %}
                                <dt class="report-dt">Address Extra</dt>
                                <dd class="report-dd">{{ order.billing_address.address_extra }}</dd>
                            {% endif %}
                            <dt class="report-dt">City</dt>
                            <dd class="report-dd">{{ order.billing_address.city }}</dd>
                            <dt class="report-dt">Postal Code</dt>
                            <dd class="report-dd report-dd-mono">{{ order.billing_address.postal_code or "-" }}</dd>
                            {% if order.billing_address.state %}
                                <dt class="report-dt">State</dt>
                                <dd class="report-dd">{{ order.billing_address.state }}</dd>
                            {% endif %}
                            <dt class="report-dt">Country</dt>
                            <dd class="report-dd report-dd-mono">{{ order.billing_address.country or "-" }}</dd>
                            {% if order.billing_address.phone_number %}
                                <dt class="report-dt">Phone</dt>
                                <dd class="report-dd report-dd-mono">{{ order.billing_address.phone_number }}</dd>
                            {% endif %}
                        </dl>
                    </div>
                {% endif %}
            </div>
        </section>
    {% endif %}
    <section class="report-section">
        <h2 class="report-section-title">Line Items</h2>
        <table class="report-table">
            <thead>
                <tr>
                    <th>Product Reference</th>
                    <th>Short Description</th>
                    <th>Gender</th>
                    <th>Size</th>
                    <th class="report-table-quantity">Unit Price</th>
                    <th class="report-table-quantity">Quantity</th>
                    <th class="report-table-quantity">Line Total</th>
                </tr>
            </thead>
            <tbody>
                {% for row in rows %}
                    <tr>
                        <td class="report-table-mono">{{ row.product_reference }}</td>
                        <td>{{ row.short_description }}</td>
                        <td>{{ row.gender }}</td>
                        <td class="report-table-mono">{{ row.size }}</td>
                        <td class="report-table-quantity">{{ "%.2f" % row.price }} {{ row.currency or "" }}</td>
                        <td class="report-table-quantity">{{ row.quantity }} x</td>
                        <td class="report-table-quantity">{{ "%.2f" % row.total }} {{ row.currency or "" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5">Total</td>
                    <td class="report-table-quantity">{{ total_units }} x</td>
                    <td class="report-table-quantity report-total-emph">{{ "%.2f" % order.total }} {{ order.currency or "" }}</td>
                </tr>
            </tfoot>
        </table>
    </section>
    <section class="report-section report-section-card">
        <h2 class="report-section-title">Totals</h2>
        <dl class="report-dl report-dl-totals">
            <dt class="report-dt">Subtotal</dt>
            <dd class="report-dd report-dd-mono">{{ "%.2f" % order.sub_total }} {{ order.currency or "" }}</dd>
            <dt class="report-dt">Discount</dt>
            <dd class="report-dd report-dd-mono">{{ "%.2f" % order.discount }} {{ order.currency or "" }}</dd>
            <dt class="report-dt">Shipping</dt>
            <dd class="report-dd report-dd-mono">{{ "%.2f" % order.shipping_cost }} {{ order.currency or "" }}</dd>
            <dt class="report-dt">Taxes</dt>
            <dd class="report-dd report-dd-mono">{{ "%.2f" % order.taxes }} {{ order.currency or "" }}</dd>
            <dt class="report-dt">Total</dt>
            <dd class="report-dd report-dd-mono report-total-emph">{{ "%.2f" % order.total }} {{ order.currency or "" }}</dd>
        </dl>
    </section>
    {% if payment_type %}
        <section class="report-section">
            <h2 class="report-section-title">Payment</h2>
            <dl class="report-dl">
                <dt class="report-dt">Type</dt>
                <dd class="report-dd report-dd-mono">{{ payment_type }}</dd>
            </dl>
        </section>
    {% endif %}
{% endblock %}
{% block report_footer %}
    Budy Order Report
{% endblock %}
